project:
  type: website

website:
  title: "rambling"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/tomjrwilliams
      - icon: linkedin
        href: https://linkedin.com/in/tomjrwilliams/
      - icon: twitter
        href: https://twitter.com/tjrwilliams
format:
  html:
    theme: flatly
    css: styles.css



