project:
  type: website

website:
  title: "rambling"
  navbar:
    left:
      - href: ./quarto/index.qmd
        text: Home
      - ./quarto/about.qmd

format:
  html:
    theme: flatly
    css: ./quarto/styles.css
    toc: true



