---
title: "Time & Elasticity"
author: "Tom Williams"
date: "2023-01-15"
categories: []
draft: true
---

This post is a collection of thoughts on the importance of time when considering price elasticities.

# Time & Elasticity

A price elasticity, often one of the first concepts introduced in a university economics programme, is the rate of change of either supply or demand for some good as one changes its price.

## Econ 101

The more elastic the supply or demand for a good, the more the variable responds to a given change in price.

For instance, one would assume that the supply of electricity from a wind farm is probably pretty inelastic w.r.t. price: a change in power prices is unlikely to have much bearing on wind speeds (and thus electricity generation), whilst the marginal cost of power generation is probably close to zero (so additional supply is all incremental profit).

In contrast, the demand for electricity from a smart-meter equipped home is probably pretty elastic, by design: the whole point of such a system is to dynamically adjust usage during the day in response to changes in price.

## Elasticity and volatility

Intuitively, given that total supply and demand (more or less) have to balance across the grid, in the presense of volatility, one would assume that inelasticity in one part of the system has to be balanced out by elasticity elsewhere.

For instance, let's assume we introduce a new wind-farm electricity supplier to the grid. On a windy day, we're going to have a bunch of extra supply, which will have to be balanced out by either a supply decrease or a demand increase elsewhere (eg. gas plants turning off, fridges turning on).

The more variable our wind-farm, the greater the elastic capacity required elsewhere for the grid to balance. More generally: as we increase the volatility of the inelastic components of supply or demand, we have to reduce their overall share.

## Inventory

Goods markets generally don't need to balance with quite the same brutality as the power grid, given that suppliers can accumulate, run down, and even write off their inventories.

Having said that, we need not lose any generality from the above: we can simply model inventory accumulation and write offs as demand components, and inventory run down as a component of supply.

Given this, we can then make the argument that - all else being equal - if we increase the volatility of demand, we have to increase our inventory capacity (see [here](..\inventory-level-under-holding-costs\index.qmd) for a demonstration in python).

## TODO

- Supply and demand = f(capacity)
- Capacity = f(time)
- -> Change supply or demand = f(time)