---
title: "Supply: f(capacity) not f(price)"
author: "Tom Williams"
date: "2023-03-04"
categories: []
draft: true
---

## 0: Intro

In this, ...

### 0.0: Current

Supply is a function of price.

Take intersection of supply and demand curve in price space, to find supply == demand at price == p.

Under relevant efficient market assumptions (non monopolistic, etc.).

Assuming utility curves, can then derive various social optimality results.

### 0.1: Proposed

Supply is - first and foremost - a function of cumulative investment in productive capacity.

Productive investment requires cash, raw materials, and time.

As such, supply is effectively fixed in the short term - beyond the flexibility provided by onhand inventory.

Because investment is expensive, it is only under-taken when expected to generate a positive return over its life.

Price is thus still relevant, but only in so far as it changes the expected RoI of incremental new capacity investment / maintenance.

### 0.2: Methodology

Show that it's either redundant, with the interesting parts of the system not modellable (without resort to a capacity model) or just outright false.

Claims:

- Supply is, aside from inventory management, short term fixed, and thus not directly a function of price.

- Supply is, instead, a function of cumulative investment to that point: which at point t is effectively fixed.

## 1: Evidence

Start with assuming the strong form, supply = f(price), show that logical / intuitions from this premise don't hold, and then progressively weaken the premise until we reach claim 2, supply = f(investment).

### 1.0: Supply = f(price) is true

If price increases, so does supply available for sale.

But, examples:

- Covid, semis

- Ukraine, oil and gas (particularly liquification capacity).

Clearly, short term price changes didn't move supply - as there wasn't any available.

Because, it clearly takes time and cost heavy investment to build capacity.

### 1.1: Shifts and elasticity

One could argue that the above can be accumulated within a supply = f(price) framework.

Shifting the supply curve to zero.

And / or flattening it, so no price impact.

But, if we allow that the supply curve can shift, and then shift back, we need a model for when it does so.

That, I'd argue, is via investment in new capacity. In that sense, shifts in supply curve drop out of the capacity investment model: so even if f(price) can accomodate, it has to rely on f(capacity) to be of use.

Similar argument against the slope, clearly price does impact supply - just over a time frame not specified in the model.

How do we specify it? With a capacity model.

So again, the part we care about in the f(price) model turns out to be completely not-representable (insufficient) variables, without resort to a capacity model.

### 1.2:  Supply = f(price) is true except in special cases

One could argue that semis and gas are unusually fixed capital intensive industries, and so special cases: in general, supply can adjust as required.

Examples:

- Pharma

- Retail (distribution)

- Retail (marketing)

- Labor

Clearly, significant time and cash (and materials) is expended ahead of time, to support future supply capability.

Rather, special cases just expose the underlying process, that is otherwise behind the scenes when running smoothly.

### 1.3: Conclusion

Either false

Or the interesting parts of the model have to be just arbitrarily assumed, but are completely external to the model

Whereas they're fully representable if not predictable by a supply = f(capacity) model.

## 2: Supply = f(price) is false but useful

Common refrain, Lucas, doesn't have to be true if (practically?) useful.

Price changes the ROI, so in the long run, we can in some sense supply is partially a function of price (even in a capacity model).

Even if it's a massive over simplification.

### 2.: Time

Essentially, f(price) is to ignore time: conflate short and long.

#### 2. Time is what we actually want to model

But arguably the key question we're interested in is probably something to do with how long it takes.

And how much it will cost.

Just saying that it will (maybe) eventually icnrease doesn't tell us anything of use at all.

What matters for price formation, and the rest of the economy depending on these outputs, is when.

If you assume that away, you can say almost whatever you like.

#### 2.: Ignores the decision part

We have to invest ahead of time in future demand

The key question in econ, business, and we assume it away.

As we'll see, not doing so makes a bunhc of toher problems much more tractable.

### 2.: Other inputs to ROI

The second thing, on top of time, is that it takes cash (over time) to invest, and we're fundamentally (mostly) interested in some kind of ROI on capcity.

#### 2.: Rates

Hence raising rates will reduce investment, see it in the employ america link to the drop in american capacity with volker shock.

Ignoring time is to ignore rates.

#### 2.: Demand

Key thing is expected future demand meeting the new capacity investment.

Ignoring time is to ignore that investing in future demand, ahead of that demand, because investment takes time.

#### 2.: Tax

Corrolary of demand, is supply side taxation is partly nonsense.

Tax will only matter to the extent its the marginal decision.

If no demand, likely just lead to cash return to investors - eg. trump cuts.

### 2.: Other inputs to capacity: non homogenous capital

The second question is that capacity takes more than just time - it takes other goods.

#### 2.: Expertise

Expertise, compounds over time.

Hence why certain countries are the only creating certain goods.

Certain firms.

Argument for targeted state support.

#### 2.: Capital goods

...

#### Natural resourcers?

### 2.: Conclusion

Because it ignores time, merges short and long term

We are unable to model - because we've assumed it away - most of the actually interesting questions.

For instance, ...

Can therefore draw arbirary lines and assert whatever we like.

## 3: Implications

THings that become modellable / intuitive once we model supply as short term fixed, f(capacity)

### 3.: Cycles

Cycles - investing ahead of demand

Assume several at once, and demand falls short: cycle

### 3.: Returns to scale

Clearly function of each industry differently.

Define the limits to investment.

When you build a single giant factory vs separate restaurants.

Interesting questions are how these interact with the cycles.

### 3.: Growth

Via investment in new productive capacity, improve rts, free investment for elsewhere

Function of demand

### 3.: Paper demand

Investing ahead of demand, often debt backed.

Therefore demand for paper is partly a funciton for noncash financed investment

Link to eg. chinese growth model.

### 3.: Price dynamics

Price will then be determined by the interaction of previous investment.

And future demand.

Where it need never clear.

## Conclusion

### 4.0: Supply = f(time) not f(price)

...

Investment function, how time and cash translates to capacity of a certain efficiency, is much more important than elasticity

And subsumes it

### 4.: Next steps

Given the investment-time to future capacity surface.

Can then look at a return on investment surface, to then get out actual investment per period.

Which then determines actual capacity.

Whether this ends up being utilised, is then a question of demand - order arrival.