---
title: "Marginal Revenue = Marginal Cost"
author: "Tom Williams"
date: "2023-03-04"
categories: []
draft: true
---

Price



Settle at the point where new investment is too expensive, not  marginal production.

Marginal change in production more accurate.

If there's a reason new investmment is more expensive than old, price can permanently exist above marginal cost.

Even if 'competitive' / efficient market (for existing players).



Many reasons why might be the case.

For instance, returns to scale allow lower pricing make it more expensive to loss-make your way into the industry.



Or actually improve the business itself, like banking to some extent in diversifying the loan book: assuming real estate, say, is a key input, they cna afford to out buy the investment goods (assuming fixed availability).



Brand value makes marginal consumer churn more expensive for new entrants.


Other kinds of sticky regulation / approval, where it becomes marginally harder to get approved once an existing supplier is in place (and has the right 'insider' relationships).






On the other hand if it gets incrementally cheaper

Eg. as knowledge diffuses of hwo to build, or consumer awareness

Get a continual flood in as the barriers go down to losing your way in

Likely a boom, followed by an over-capacity bust and consolidation



In which case price is well below marginal cost, because forced to utilise capacity to meet external requirements.

Until bankrupt and absorbed (for instance).



#### TBC: vol premia

If not included, and some diversification to scale, industry will tend to consolidate just on through-cycle vol.