---
title: "Demand (Corporate): f(capacity, demand) not f(price)"
author: "Tom Williams"
date: "2023-03-04"
categories: []
draft: true
---

Corporate demand even as a function of accumulated capacity (and downstram demand, and then profitability).

Price only via profitability.

# 0:: Intro

## 0.: Price is f (price)

Intersection with supply f(price)

## 0.: Reality

### Input 

If input good

Function also of capacity

At the limit

Within that limit, of inventory needs (orders)

### Investment good

For investment good, just is the investment

So function of long term demand expectation, rpimarily.

### Consumer good?

## 0.: Methodology

Similar to supply

Argue that either wrong conclusions, or without content without the adition of either capacity function (and inventory), or just is investment. 

# 1.: Evidence

## 1.0: Demand = f(price) is true

But, eg. energy

Have to pay - though can reduce usage.

To the extent their are complimentary goods that full fil the same purpose and that have capital that supports.

## 1.1: Just model with inelasticity

But not in the long run.

We get the same issue as supply: we ignore the one variable that is the key question

How long does it take for us to shift production away from a given input good

And how epxensive does it have to get for us to do so

Essentially, specifying the elasticity: but that should be our goal, to take it as assumed is to take as given what we want to investigate.

## 1.2: Demand = f(price) is true except special cases

Really, the special case is when it's true: investment

But that's just as much if not more about the total cost vs return - ie. expected future demand.

# 2: Demand = f(price) is false but useful 

## 1.: Profitability

Of the capital, with units of investment good

If output has gone up, will have no effect on demand.

## 1.: Funding  / cash availablility

Arguably the key thing it misses is cash availability.

If we're separating short from long.

Which doesn't change anything about the slope of the curve, but rather shifts it.

But as above, can arbitrarily assume a shift: but that's exactly what we should be modelling.

# 3.: Benefits / implications / now answerable if f(capacity)

## 1.: Market number vs rate

Number of participants vs rate per participant

Could be very different, need to break out

As may not be constant over time

Which 

# 4.: Conclusions



#### Aside

Demand should be modelled as a probabilistic (order) arrival process of time t, where the price is one element of a state vector indexed on t.

Highlights that we only have local, historic, knowledge of demand response.

#### Aside

Which in turn makes clear a market need not clear for long periods of time.

Can have many more orders than fills, without capacity necessarily changing (or demand being able to change).